version: "3.9"

services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/code
    #    networks:
    #      - backbone
    ports:
      - "3000:3000"
#  nginx:
#    image: nginx
#    container_name: nginx
#    volumes:
#      - ./nginx-configs:/etc/nginx/conf.d
#    ports:
#      - "80:80"
#    networks:
#      - backbone
volumes:
  web_front:


networks:
  backbone:
    driver: bridge