version: "3.9"

services:
  web:
    build: .
    command: npm start
    volumes:
      - .:/code
    networks:
      - my-proxy-net
      - default
    ports:
      - "3000:3000"



      #  nginx:
      #    image: nginx
      #    container_name: nginx
      #    volumes:
      #      - ./nginx-configs:/etc/nginx/conf.d
      #    ports:
#        - "80:80"

volumes:
  web_front:

networks:
  my-proxy-net:
    external:
      name: sm64fantasy_api
